"""subscription_email

Revision ID: 7b2c3c6d8596
Revises: 6efed3948da3
Create Date: 2022-01-28 11:47:44.080041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2c3c6d8596'
down_revision = '6efed3948da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_email_email'), 'subscription_email', ['email'], unique=True)
    op.create_index(op.f('ix_subscription_email_id'), 'subscription_email', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_email_id'), table_name='subscription_email')
    op.drop_index(op.f('ix_subscription_email_email'), table_name='subscription_email')
    op.drop_table('subscription_email')
    # ### end Alembic commands ###
